DROP TABLE IF EXISTS permission    CASCADE;
DROP TABLE IF EXISTS book          CASCADE;
DROP TABLE IF EXISTS account       CASCADE;

CREATE TABLE account (
	id                  BIGINT          NOT NULL    GENERATED BY DEFAULT AS IDENTITY,
	account_name        VARCHAR(100)    NOT NULL,
	email               VARCHAR(100)    NOT NULL,
	account_password    VARCHAR(100)    NOT NULL,
	active              BOOLEAN         NOT NULL
);

ALTER TABLE user ADD CONSTRAINT pk_account PRIMARY KEY (id);
ALTER TABLE user ADD CONSTRAINT uk_account_email UNIQUE (email);

CREATE TABLE permission (
	id          BIGINT          NOT NULL    GENERATED BY DEFAULT AS IDENTITY,
	function    VARCHAR(100)    NOT NULL,
	account_id  BIGINT          NOT NULL
);

ALTER TABLE permission ADD CONSTRAINT pk_permission PRIMARY KEY (id);
ALTER TABLE permission ADD CONSTRAINT uk_permission UNIQUE (function, account_id);
ALTER TABLE permission ADD CONSTRAINT fk_permission_account FOREIGN KEY (account_id) REFERENCES account;

CREATE TABLE book (
	id              BIGINT          NOT NULL    GENERATED BY DEFAULT AS IDENTITY,
	title           VARCHAR(100)    NOT NULL,
	status          VARCHAR(50)     NOT NULL,
	inclusion_date  DATE            NOT NULL,
	devolution_date DATE,
	account_id      BIGINT
);

ALTER TABLE books ADD CONSTRAINT pk_book PRIMARY KEY (id);
ALTER TABLE books ADD CONSTRAINT uk_book UNIQUE (title);
ALTER TABLE books ADD CONSTRAINT fk_book_account FOREIGN KEY (account_id) REFERENCES account;